### ISSUE TITLE
Notice since PW 3.0.43

### ISSUE THREAD

**Issue by m-knorr** [horst-n/CroppableImage3#2]
Since the last update from friday night, I get on specific image fields the following Notice:

`Notice:  Only variables should be passed by reference in "site/modules/CroppableImage3/ProcessCroppableImage3/ProcessCroppableImage3.module" on line 65`

The cropping works as expected, but the frontend output won't work anymore. The `getCrop` method seems not to deliver an object anymore!

Due to my first investigations in only occurs on multi-image fields.

**Comment by horst-n** [comment]
Hi @m-knorr 
I don't have this here, using PW 3.0.43 and latest CI3, and PHP 5.6.x. 
Maybe, you use another PHP version?
If this is still issuing, you may try to use ``$field->name`` instead of simply ``$field``. (?)

**Comment by ghost** [comment]
I have the same problem. Just upgraded to a newer version (3.52 on dev) and i get this error: **Trying to get property of non-object**. Below my function.  **$image->url** is retrieved but not **$image->getCrop('miniature')->url**
`function uneImageAlbum($image) {
  return '<a href="'. $image->url. '" data-fancybox="images"><img src="' .$image->getCrop('miniature')->url.'" alt="" /></a>';
}`

**Comment by horst-n** [comment]
you may read on here in forum: https://processwire.com/talk/topic/14090-croppable-image-3/?page=5#comment-137789
and following.
It turned out, that all those installations aren't up-to-date with the last repo 0.9.17, due to an issue with PWs updatemodule and my module. ATM we try to find out why the update mechanism doesn't work here.
